/* ============================================
   SESSION CONTENT DATA — All 6 Sessions
   ============================================ */
const sessionContent = {
session1: {
    hero: { title: 'Session 1: Introduction to Cyber Security in Manufacturing', desc: 'Understand why manufacturing is the most targeted industry, learn the CIA Triad, and explore real-world cyberattacks on industrial systems.' },
    concepts: [
        { title:'🏭 Why Cybersecurity in Manufacturing?', body:`<p>Manufacturing is the <strong>most targeted industry</strong> for cyberattacks (ransomware, espionage). Modern factories rely heavily on automation and connected systems (ICS, IoT, SCADA).</p><p><strong>Impacts:</strong> Production halts, safety risks, financial loss ($70M+ for Norsk Hydro), IP theft</p>` },
        { title:'🔐 The CIA Triad', body:`<table class="info-table"><tr><th>Principle</th><th>Focus</th><th>Threat if Violated</th><th>Protection</th></tr><tr><td><strong>Confidentiality</strong></td><td>Prevent unauthorized access</td><td>Data leaks, espionage</td><td>Encryption, access control</td></tr><tr><td><strong>Integrity</strong></td><td>Ensure data is unchanged</td><td>Data tampering, fraud</td><td>Hashing, digital signatures</td></tr><tr><td><strong>Availability</strong></td><td>Ensure access when needed</td><td>Downtime, DDoS, ransomware</td><td>Backups, redundancy, failover</td></tr></table><p>Every security control — firewalls, auth, antivirus — ultimately protects C, I, or A.</p>` },
        { title:'💻 IT vs OT — The Critical Difference', body:`<table class="info-table"><tr><th>Aspect</th><th>IT (Information Tech)</th><th>OT (Operational Tech)</th></tr><tr><td>Focus</td><td>Data management & security</td><td>Physical process control</td></tr><tr><td>Examples</td><td>Email, ERP, CRM, cloud</td><td>PLCs, SCADA, HMI, sensors</td></tr><tr><td>Priorities</td><td>Confidentiality & Integrity</td><td>Availability & Safety</td></tr><tr><td>Lifecycle</td><td>3-5 years refresh</td><td>10-20+ years</td></tr><tr><td>Patching</td><td>Frequent updates</td><td>Rare — fear of downtime</td></tr><tr><td>Users</td><td>Office workers, IT admins</td><td>Engineers, technicians</td></tr></table>` },
        { title:'⚡ Cyber-Physical Systems (CPS)', body:`<p>CPS integrates <strong>computation, networking, and physical processes</strong> with feedback loops. Sensors gather data → Controllers/PLCs decide → Actuators respond → Networks connect everything.</p><p><strong>Examples:</strong> Automated robotic assembly lines, smart energy management, remote SCADA infrastructure, predictive maintenance using IIoT + AI.</p><p>CPS is the core of <strong>Industry 4.0 and 5.0</strong>, making cybersecurity essential for operational continuity and human safety.</p>` },
        { title:'🎯 Attack Surface, Threat Vectors & Attack Vectors', body:`<table class="info-table"><tr><th>Term</th><th>Definition</th><th>Example</th></tr><tr><td><strong>Threat Vector</strong></td><td>Potential path for threats to enter</td><td>USB ports, VPN, email, IoT devices</td></tr><tr><td><strong>Attack Vector</strong></td><td>Actual method used to exploit</td><td>RDP brute-force, phishing link</td></tr><tr><td><strong>Attack Surface</strong></td><td>Total area exposed to threats</td><td>All connected devices, open ports, people</td></tr></table><p><strong>Reducing attack surface:</strong> Zero Trust, network segmentation, patch management, disable unused ports/services.</p>` },
        { title:'🔓 OT Vulnerabilities', body:`<ul><li><strong>Lack of encryption/authentication</strong> in legacy systems — attackers can intercept or inject commands</li><li><strong>Poor patching practices</strong> — updates delayed for uptime, known vulnerabilities exploitable for months</li><li><strong>Human errors & social engineering</strong> — phishing, misconfigurations, USB misuse</li><li><strong>Default passwords & remote access misuse</strong> — brute-force attacks, unauthorized access via RDP/TeamViewer</li></ul>` },
        { title:'💰 Business & Safety Impacts', body:`<table class="info-table"><tr><th>Impact</th><th>Example</th></tr><tr><td>Financial Losses</td><td>Colonial Pipeline: $4.4M ransom + days of downtime</td></tr><tr><td>Supply Chain Disruption</td><td>Norsk Hydro: global aluminum supply disrupted</td></tr><tr><td>Equipment Damage</td><td>Stuxnet: ~1,000 centrifuges physically destroyed</td></tr><tr><td>Safety Hazards</td><td>Oldsmar: attempted to poison water supply with lye</td></tr><tr><td>Reputation & Trust</td><td>Target breach: millions of customer records exposed</td></tr></table>` }
    ],
    caseStudies: [
        { name:'Stuxnet (2010)', detail:'Targeted Siemens PLCs in Iran\'s nuclear facility via USB. Reprogrammed centrifuges to spin at damaging speeds while showing normal readings. First known cyber-physical weapon.', impact:'~1,000 centrifuges destroyed, delayed nuclear program', lesson:'Even air-gapped OT systems can be compromised.' },
        { name:'Norsk Hydro / LockerGoga (2019)', detail:'Ransomware hit IT systems, cascading to production shutdown in multiple plants globally. Employees used pen and paper.', impact:'$60-70M in damages, production halted weeks', lesson:'IT-OT dependency means IT breach = OT disruption.' },
        { name:'Colonial Pipeline (2021)', detail:'DarkSide ransomware breached IT billing systems. Pipeline voluntarily shut down OT operations fearing lateral movement.', impact:'Fuel shortages across US East Coast, $4.4M ransom paid', lesson:'No segmentation + no MFA = catastrophic breach.' },
        { name:'Oldsmar Water (2021)', detail:'Attacker used TeamViewer (no MFA) to access HMI and increased sodium hydroxide from 100 to 11,100 ppm.', impact:'Near-poisoning of water supply. Caught by alert operator.', lesson:'Basic cyber hygiene failures can threaten public safety.' }
    ],
    flashcards: [
        { front:'CIA Triad', back:'Confidentiality, Integrity, Availability — the three pillars of information security.' },
        { front:'OT vs IT Priority', back:'OT prioritizes Availability & Safety. IT prioritizes Confidentiality & Integrity.' },
        { front:'Attack Surface', back:'The total area of a system exposed to threats — every device, port, person, and protocol.' },
        { front:'Stuxnet Significance', back:'First known malware to target ICS for physical sabotage. Proved cyber attacks can cause kinetic damage.' },
        { front:'Zero Day', back:'A vulnerability unknown to the vendor with no patch available — highest risk in OT due to long lifecycles.' }
    ]
},
session2: {
    hero: { title:'Session 2: Networking Concepts & Commands', desc:'Master OSI & TCP/IP models, IP addressing, network devices, protocols, and essential security tools like Wireshark.' },
    concepts: [
        { title:'🌐 Network Types', body:`<table class="info-table"><tr><th>Type</th><th>Coverage</th><th>Example</th></tr><tr><td><strong>PAN</strong></td><td>Few meters</td><td>Bluetooth phone ↔ smartwatch</td></tr><tr><td><strong>LAN</strong></td><td>Building/campus</td><td>Office computers + printers on one router</td></tr><tr><td><strong>MAN</strong></td><td>City/metro</td><td>University inter-campus network</td></tr><tr><td><strong>WAN</strong></td><td>Countries/global</td><td>The Internet</td></tr></table><p><strong>Architectures:</strong> Client-Server (centralized, e.g., Google Drive) vs Peer-to-Peer (distributed, e.g., BitTorrent)</p>` },
        { title:'📡 OSI Model (7 Layers)', body:`<table class="info-table"><tr><th>Layer</th><th>Function</th><th>Protocols</th><th>Threats</th><th>Defense</th></tr><tr><td>7. Application</td><td>User interface</td><td>HTTP, SMTP, DNS</td><td>Malware, phishing</td><td>Antivirus, secure coding</td></tr><tr><td>6. Presentation</td><td>Format/encrypt</td><td>SSL/TLS, JPEG</td><td>Weak encryption</td><td>Strong TLS</td></tr><tr><td>5. Session</td><td>Manage sessions</td><td>NetBIOS</td><td>Session hijacking</td><td>Token auth, timeout</td></tr><tr><td>4. Transport</td><td>Delivery control</td><td>TCP, UDP</td><td>SYN flood, port scan</td><td>Firewalls, rate-limit</td></tr><tr><td>3. Network</td><td>Routing</td><td>IP, ICMP</td><td>IP spoofing</td><td>ACLs, VPNs</td></tr><tr><td>2. Data Link</td><td>MAC/Switching</td><td>ARP, Ethernet</td><td>ARP spoofing</td><td>Port security</td></tr><tr><td>1. Physical</td><td>Bit transmission</td><td>Cables, Wi-Fi</td><td>Tampering</td><td>Locks, shielding</td></tr></table>` },
        { title:'🔢 IP Addressing & Subnetting', body:`<p><strong>IPv4:</strong> 32-bit address (e.g., 192.168.1.1). Private ranges: 10.x.x.x, 172.16-31.x.x, 192.168.x.x</p><p><strong>Subnetting:</strong> Divides networks into smaller segments. CIDR notation /24 = 255.255.255.0 = 254 usable hosts.</p><table class="info-table"><tr><th>Class</th><th>Range</th><th>Default Mask</th><th>Hosts/Network</th></tr><tr><td>A</td><td>1-126</td><td>/8</td><td>~16 million</td></tr><tr><td>B</td><td>128-191</td><td>/16</td><td>~65,000</td></tr><tr><td>C</td><td>192-223</td><td>/24</td><td>254</td></tr></table><p><strong>MAC Address:</strong> 48-bit hardware identifier (e.g., 00:1A:2B:3C:4D:5E). Used at Layer 2 for local device identification.</p>` },
        { title:'🔌 Network Devices', body:`<table class="info-table"><tr><th>Device</th><th>Function</th><th>Key Feature</th></tr><tr><td><strong>Hub</strong></td><td>Broadcasts to all</td><td>No intelligence (legacy)</td></tr><tr><td><strong>Switch</strong></td><td>Forwards to specific device</td><td>Uses MAC addresses (L2)</td></tr><tr><td><strong>Router</strong></td><td>Connects networks</td><td>Uses IP addresses (L3)</td></tr><tr><td><strong>Firewall</strong></td><td>Filters traffic by rules</td><td>Block unauthorized access</td></tr><tr><td><strong>Access Point</strong></td><td>Extends wireless coverage</td><td>Wi-Fi capability</td></tr></table><p><strong>Firewall types:</strong> Packet-filtering, Stateful inspection, Application-level, Next-Gen (NGFW)</p><p><strong>VLANs:</strong> Logical network grouping for segmentation. VLAN 10 = Marketing, VLAN 20 = Engineering</p>` },
        { title:'📊 Ports & Protocols', body:`<table class="info-table"><tr><th>Protocol</th><th>Port</th><th>TCP/UDP</th><th>Description</th></tr><tr><td>HTTP</td><td>80</td><td>TCP</td><td>Web traffic</td></tr><tr><td>HTTPS</td><td>443</td><td>TCP</td><td>Secure web (TLS)</td></tr><tr><td>SSH</td><td>22</td><td>TCP</td><td>Secure remote login</td></tr><tr><td>FTP</td><td>21</td><td>TCP</td><td>File transfer</td></tr><tr><td>DNS</td><td>53</td><td>UDP/TCP</td><td>Name resolution</td></tr><tr><td>DHCP</td><td>67/68</td><td>UDP</td><td>Dynamic IP assignment</td></tr><tr><td>RDP</td><td>3389</td><td>TCP</td><td>Remote Desktop</td></tr><tr><td>Modbus</td><td>502</td><td>TCP</td><td>Industrial control</td></tr><tr><td>SNMP</td><td>161</td><td>UDP</td><td>Network monitoring</td></tr></table><p><strong>TCP vs UDP:</strong> TCP = reliable, ordered (web, email). UDP = fast, no guarantee (streaming, DNS).</p>` },
        { title:'🛡️ Network Security: IDS, IPS, DMZ', body:`<p><strong>IDS</strong> = Intrusion Detection System — monitors and alerts. <strong>IPS</strong> = Intrusion Prevention System — detects AND blocks. IDS is out-of-path; IPS is inline.</p><p><strong>DMZ</strong> = Demilitarized Zone — a buffer between external (internet) and internal (LAN) networks. Hosts public-facing servers while isolating internal resources.</p><p><strong>Network Segmentation</strong> divides the network to limit lateral movement, improve performance, and simplify monitoring.</p>` },
        { title:'🔧 Essential Tools', body:`<ul><li><strong>ping</strong> — Tests host reachability using ICMP echo requests</li><li><strong>traceroute/tracert</strong> — Shows path packets take, reveals each hop</li><li><strong>netstat -an</strong> — Displays active connections and open ports</li><li><strong>ipconfig/ifconfig</strong> — Shows IP configuration of interfaces</li><li><strong>Wireshark</strong> — Graphical packet analyzer for real-time capture, deep inspection, protocol analysis</li></ul>` }
    ],
    caseStudies: [],
    flashcards: [
        { front:'OSI Layer 7', back:'Application Layer — User-facing protocols (HTTP, DNS, SMTP). Threats: phishing, malware.' },
        { front:'TCP 3-Way Handshake', back:'SYN → SYN-ACK → ACK. Establishes reliable connection. SYN flood = DoS attack exploiting this.' },
        { front:'DHCP DORA', back:'Discover → Offer → Request → Acknowledge. How devices get IP addresses automatically.' },
        { front:'ARP Spoofing', back:'Attacker sends fake ARP replies to associate their MAC with another IP, enabling MitM attacks.' },
        { front:'Port 443 vs 80', back:'443 = HTTPS (encrypted), 80 = HTTP (unencrypted). Always use HTTPS for security.' }
    ]
},
session3: {
    hero: { title:'Session 3: Enterprise IT Network Security', desc:'Explore enterprise network architecture, OWASP Top 10, Zero Trust, and layered defense strategies.' },
    concepts: [
        { title:'🏢 Enterprise IT Network', body:`<p>A structured system of hardware, software, and protocols supporting communication and data flow. It's the backbone of business operations.</p><p><strong>Must ensure:</strong> Confidentiality, Integrity, Availability (CIA)</p><p><strong>Key components:</strong> LAN (switches, routers, firewalls), Data Centers (servers, storage, databases), Cloud services</p>` },
        { title:'🔟 OWASP Top 10 (2023)', body:`<table class="info-table"><tr><th>#</th><th>Risk</th><th>Example</th><th>Mitigation</th></tr><tr><td>A1</td><td>Broken Access Control</td><td>URL manipulation to see others' data</td><td>RBAC, validate IDs</td></tr><tr><td>A2</td><td>Cryptographic Failures</td><td>Passwords stored in plaintext</td><td>TLS, bcrypt/Argon2</td></tr><tr><td>A3</td><td>Injection</td><td>SQL: ' OR '1'='1 bypasses login</td><td>Parameterized queries</td></tr><tr><td>A4</td><td>Insecure Design</td><td>Unlimited login attempts → brute force</td><td>Threat modeling, rate limiting</td></tr><tr><td>A5</td><td>Security Misconfiguration</td><td>Default admin/admin credentials</td><td>Change defaults, patch regularly</td></tr><tr><td>A6</td><td>Vulnerable Components</td><td>Outdated libraries (Equifax breach)</td><td>Dependency scanning, npm audit</td></tr><tr><td>A7</td><td>Auth Failures</td><td>Weak passwords, no MFA</td><td>Strong password rules, MFA</td></tr><tr><td>A8</td><td>Software Integrity</td><td>Updates from untrusted sources</td><td>Code signatures, checksums</td></tr><tr><td>A9</td><td>Logging Failures</td><td>No logs for failed logins</td><td>SIEM, centralized logging</td></tr><tr><td>A10</td><td>SSRF</td><td>Server requests internal systems</td><td>Whitelist domains</td></tr></table>` },
        { title:'🔒 Zero Trust Architecture', body:`<p><strong>"Never trust, always verify"</strong></p><ul><li>Validate user/device identity continuously</li><li>Enforce micro-segmentation</li><li>Principle of least privilege</li><li>Suited for hybrid/cloud environments</li><li>Every access request is fully authenticated, authorized, and encrypted</li></ul>` },
        { title:'🛡️ Defense-in-Depth', body:`<table class="info-table"><tr><th>Layer</th><th>Protection</th><th>Example</th></tr><tr><td>Perimeter</td><td>Firewalls, IDS/IPS</td><td>Blocking suspicious traffic at the edge</td></tr><tr><td>Network</td><td>VLANs, NAC</td><td>Segmenting IT from OT networks</td></tr><tr><td>Endpoint</td><td>Antivirus, EDR</td><td>Anti-malware on production PCs</td></tr><tr><td>Application</td><td>Code reviews, WAF</td><td>Filtering SQL injection attempts</td></tr><tr><td>Data</td><td>Encryption, DLP</td><td>AES-256 for stored design files</td></tr><tr><td>User</td><td>MFA, training</td><td>Phishing awareness programs</td></tr></table><p>Even if one layer fails (hacker bypasses firewall), the others still protect the system.</p>` },
        { title:'⚠️ Security Misconfigurations', body:`<ul><li><strong>Open ports</strong> — Unnecessary ports left exposed for attacker scanning</li><li><strong>Default credentials</strong> — Factory-set usernames/passwords unchanged</li><li><strong>Unrestricted admin access</strong> — Admin panels accessible without restrictions</li><li><strong>Lack of segmentation</strong> — Flat networks let attackers move freely</li><li><strong>Weak firewall rules</strong> — Allowing broad or unnecessary access</li></ul>` },
        { title:'☁️ Cloud Security Challenges', body:`<ul><li><strong>Shared responsibility confusion</strong> — Misunderstanding who secures what</li><li><strong>Data leakage/misconfiguration</strong> — Public S3 buckets, exposed databases</li><li><strong>Insecure APIs</strong> — Weak or unprotected endpoints = direct attack surface</li><li><strong>Weak IAM</strong> — Improper policies allowing privilege escalation</li><li><strong>Vendor lock-in</strong> — Hard to migrate, risky dependency</li></ul>` }
    ],
    caseStudies: [],
    flashcards: [
        { front:'OWASP #1 Risk', back:'Broken Access Control — users can act outside their intended permissions.' },
        { front:'Zero Trust Principle', back:'"Never trust, always verify" — validate every user, device, and connection continuously.' },
        { front:'Defense-in-Depth', back:'Multiple overlapping security layers. If one fails, others still protect the system.' },
        { front:'SIEM', back:'Security Information and Event Management — collects and analyzes logs for real-time threat detection.' }
    ]
},
session4: {
    hero: { title:'Session 4: Industrial Networks & Criticality in OT', desc:'Deep dive into PLCs, SCADA, DCS, the Purdue Model, and identifying critical systems in OT environments.' },
    concepts: [
        { title:'⚙️ PLC — Programmable Logic Controller', body:`<p>Industrial computer for <strong>real-time control</strong> of machinery. Executes ladder logic or structured text programming.</p><p><strong>Examples:</strong> Motor control, conveyor belts, temperature regulation</p><p><strong>Security Challenges:</strong></p><ul><li>Designed for availability, not security</li><li>Weak/hardcoded credentials (admin/admin)</li><li>No encryption — commands sent in plain text</li><li>Rarely updated — patching risks downtime</li><li>Exposed via remote access, USB, vendor maintenance</li></ul>` },
        { title:'🖥️ SCADA — Supervisory Control & Data Acquisition', body:`<p>Centralized system for monitoring and controlling remote industrial equipment. The "brain and eyes" of industrial systems.</p><table class="info-table"><tr><th>Component</th><th>Role</th></tr><tr><td>RTUs</td><td>Collect data from field devices</td></tr><tr><td>PLCs</td><td>Local controllers automating responses</td></tr><tr><td>SCADA Software</td><td>Centralized monitoring, control, visualization</td></tr><tr><td>HMI</td><td>Operator dashboard/screens</td></tr></table><p><strong>Used in:</strong> Power grids, oil & gas, water systems, manufacturing, transportation</p>` },
        { title:'🔄 DCS vs SCADA', body:`<table class="info-table"><tr><th>Feature</th><th>DCS</th><th>SCADA</th></tr><tr><td>Primary Use</td><td>Continuous process control</td><td>Supervisory monitoring over wide areas</td></tr><tr><td>Control Type</td><td>Closed-loop (automatic)</td><td>Open-loop (operator intervention)</td></tr><tr><td>Response Time</td><td>Milliseconds</td><td>Seconds to minutes</td></tr><tr><td>Scalability</td><td>Limited to plant</td><td>Highly scalable, large regions</td></tr><tr><td>Examples</td><td>Refineries, power generation</td><td>Water distribution, electric grids</td></tr></table>` },
        { title:'🏗️ Purdue Model (PERA)', body:`<p>Hierarchical framework organizing ICS networks into levels 0-4 + DMZ:</p><table class="info-table"><tr><th>Level</th><th>Name</th><th>Function</th><th>Examples</th></tr><tr><td>0</td><td>Physical Process</td><td>Actual equipment</td><td>Sensors, actuators, motors</td></tr><tr><td>1</td><td>Basic Control</td><td>Automated decision-making</td><td>PLCs, drives, IEDs</td></tr><tr><td>2</td><td>Supervisory</td><td>Monitoring & control</td><td>SCADA, HMI</td></tr><tr><td>3</td><td>Operations</td><td>Production management</td><td>MES, historian, batch mgmt</td></tr><tr><td>DMZ</td><td>Buffer Zone</td><td>Secure bridge IT↔OT</td><td>Firewalls, IPS, jump servers</td></tr><tr><td>4</td><td>Enterprise</td><td>Business systems</td><td>ERP, email, cloud, CRM</td></tr></table><p><strong>Security:</strong> DMZ between L3 and L4 prevents OT/IT compromise. Never connect L0-2 directly to internet.</p>` },
        { title:'🎯 PLC Attacks & Vulnerabilities', body:`<table class="info-table"><tr><th>Attack</th><th>Description</th><th>Mitigation</th></tr><tr><td>Bypass Logic</td><td>Alters register values bypassing control logic</td><td>Memory integrity checks, restrict write access</td></tr><tr><td>Force Output</td><td>Exploits unauthenticated access to control motors/valves</td><td>RBAC, MFA, firewall</td></tr><tr><td>Replay</td><td>Captures and resends valid PLC packets</td><td>Timestamps, sequence numbers, encryption</td></tr><tr><td>MitM</td><td>Intercepts PLC ↔ engineering software communication</td><td>TLS/VPN, mutual authentication</td></tr><tr><td>S7 Auth Bypass</td><td>Exploits weak Siemens protocol authentication</td><td>Encrypted auth, network segmentation</td></tr></table>` },
        { title:'🔍 Critical Systems Identification', body:`<p>Systems whose failure/compromise causes: major safety incidents, production shutdowns, data breaches, regulatory non-compliance.</p><p><strong>Classification criteria:</strong></p><ul><li>Impact on Safety — Will failure cause injury?</li><li>Impact on Operations — Will it stop production?</li><li>Cyber Exposure — Connected to external networks?</li><li>Redundancy — Backups available?</li><li>Compliance — Subject to audits?</li></ul><p><strong>Tools:</strong> Asset Inventory, Purdue Mapping, Risk Matrix (Likelihood × Impact), FMEA/HAZOP</p>` }
    ],
    caseStudies: [],
    flashcards: [
        { front:'Purdue Level 0', back:'Physical Process layer — sensors, actuators, motors, valves. The actual equipment.' },
        { front:'Purdue Level 2', back:'Supervisory Control — SCADA systems and HMIs for monitoring and operator interaction.' },
        { front:'DCS vs SCADA', back:'DCS = localized, continuous process control (milliseconds). SCADA = supervisory monitoring over wide areas (seconds).' },
        { front:'Force Output Attack', back:'Exploits unauthenticated "force outputs" on PLCs to remotely change motors/valves without any login.' }
    ]
},
session5: {
    hero: { title:'Session 5: Industrial Protocols', desc:'Understand Modbus, DNP3, and Profibus — how they work, their security weaknesses, and how to defend them.' },
    concepts: [
        { title:'📡 What Are Industrial Protocols?', body:`<p>Communication rules between devices in OT/ICS environments. Used for PLCs, SCADA, RTUs, sensors, and actuators to enable <strong>real-time data exchange</strong>.</p><p>Key protocols: <strong>Modbus</strong> (simple, universal), <strong>DNP3</strong> (utilities/energy), <strong>Profibus</strong> (European factory automation)</p>` },
        { title:'🔧 Modbus Protocol', body:`<p>Developed by Modicon (1979). Master-Slave architecture. Most widely used industrial protocol.</p><p><strong>Security Concerns:</strong></p><ul><li>❌ No authentication — valid address + function code = access</li><li>❌ No encryption — commands sent as clear text</li><li>❌ No message checksum (TCP variant)</li><li>❌ No broadcast suppression (serial variant)</li><li>⚠️ Intentionally programmable — designed to reprogram controllers</li></ul><table class="info-table"><tr><th>Threat</th><th>Example</th><th>Mitigation</th></tr><tr><td>False Data Injection</td><td>Fake sensor readings to SCADA</td><td>VPN encrypted tunnel</td></tr><tr><td>Unauthorized Commands</td><td>"Turn Pump ON" repeatedly</td><td>Firewall with DPI</td></tr><tr><td>Denial of Service</td><td>Flood slave with requests</td><td>Network isolation</td></tr></table>` },
        { title:'⚡ DNP3 Protocol', body:`<p>Distributed Network Protocol — designed for <strong>electric utilities</strong>. Master-Outstation communication. Reliable in noisy environments, supports timestamped data.</p><p><strong>Legacy DNP3 lacks encryption</strong> — fixed in <strong>Secure DNP3 (DNP3-SA)</strong> which adds authentication, encryption, and anti-replay.</p><table class="info-table"><tr><th>Threat</th><th>Scenario</th><th>Mitigation</th></tr><tr><td>Spoofing</td><td>Fake "Open Breaker" → targeted blackout</td><td>DNP3-SA authentication</td></tr><tr><td>MitM</td><td>Alter "Breaker Tripped" to "Breaker OK"</td><td>DNP3-SA encryption</td></tr><tr><td>Replay</td><td>Resend valid commands during maintenance</td><td>Anti-replay mechanisms</td></tr><tr><td>DoS</td><td>Flood IED during storm</td><td>Segmentation, IDS</td></tr></table>` },
        { title:'🏭 Profibus Protocol', body:`<p>Developed by Siemens (1980s). Two variants:</p><ul><li><strong>Profibus-DP</strong> — High-speed factory automation (up to 12 Mbit/s), RS-485 layer</li><li><strong>Profibus-PA</strong> — Process automation in hazardous areas, intrinsically safe, bus-powered</li></ul><p><strong>Weaknesses:</strong> Proprietary, no built-in security, unencrypted traffic, no authentication.</p><table class="info-table"><tr><th>Threat</th><th>Example</th><th>Mitigation</th></tr><tr><td>Command Injection</td><td>Fake command to open filling valve</td><td>Network segmentation, firewalls</td></tr><tr><td>MitM</td><td>Intercept "tank full" signal → overflow</td><td>Physical security, strict segmentation</td></tr><tr><td>DoS</td><td>Junk messages disrupt time-critical comms</td><td>Secure gateways</td></tr></table>` },
        { title:'🔒 Protocol Security Comparison', body:`<table class="info-table"><tr><th>Concern</th><th>Modbus</th><th>DNP3</th><th>Profibus</th></tr><tr><td>Authentication</td><td>❌ None</td><td>✅ DNP3-SA adds it</td><td>❌ None</td></tr><tr><td>Encryption</td><td>❌ Clear-text</td><td>✅ DNP3-SA adds it</td><td>❌ Clear-text</td></tr><tr><td>Anti-Replay</td><td>❌ No</td><td>✅ In secure variant</td><td>❌ No</td></tr><tr><td>Best Defense</td><td>VPN + DPI firewall</td><td>Upgrade to DNP3-SA</td><td>Physical security + segmentation</td></tr></table>` }
    ],
    caseStudies: [],
    flashcards: [
        { front:'Modbus Year & Creator', back:'1979, by Modicon. Oldest and most widely used industrial protocol. Master-Slave architecture.' },
        { front:'DNP3-SA', back:'Secure Authentication variant of DNP3. Adds authentication, encryption, and anti-replay to fix legacy vulnerabilities.' },
        { front:'Profibus DP vs PA', back:'DP = Decentralized Peripherals (fast factory automation, 12 Mbit/s). PA = Process Automation (hazardous areas, intrinsically safe).' }
    ]
},
session6: {
    hero: { title:'Session 6: Cloud Security', desc:'Understand cloud security challenges, shared responsibility, IAM, and best practices for securing cloud environments.' },
    concepts: [
        { title:'☁️ Cloud Security Challenges', body:`<table class="info-table"><tr><th>Challenge</th><th>Description</th><th>Example</th></tr><tr><td>Shared Responsibility Confusion</td><td>Provider secures infrastructure; customer secures data/access</td><td>Customer thinks provider handles everything → data exposed</td></tr><tr><td>Data Leakage</td><td>Misconfigured storage exposes sensitive data</td><td>Public S3 bucket leaking customer records</td></tr><tr><td>Insecure APIs</td><td>Weak API endpoints = direct attack surface</td><td>API with no authentication allows data extraction</td></tr><tr><td>Weak IAM</td><td>Improper policies allow privilege escalation</td><td>Intern with admin access to production databases</td></tr><tr><td>Vendor Lock-in</td><td>Dependency on single provider</td><td>Migration from AWS to Azure requires rewrite</td></tr></table>` },
        { title:'🔐 Cloud Security Best Practices', body:`<ul><li><strong>Encrypt data at rest (AES-256) and in transit (TLS/SSL)</strong><br>— Healthcare app encrypts patient records in cloud DB, doctor accesses via HTTPS</li><li><strong>Use MFA (Multi-Factor Authentication)</strong><br>— Password + OTP from phone. Even stolen password can't be used alone</li><li><strong>Audit permissions regularly (PoLP)</strong><br>— Interns should NOT have admin rights. Regular audits catch excess privileges</li><li><strong>Use CSPM tools</strong><br>— Auto-detect misconfigurations: public S3 buckets, open security groups</li><li><strong>Enable continuous monitoring (SIEM)</strong><br>— Detect brute-force attempts, unusual logins, anomalous data transfers</li></ul>` },
        { title:'🛡️ Shared Responsibility Model', body:`<table class="info-table"><tr><th>Layer</th><th>Cloud Provider</th><th>Customer</th></tr><tr><td>Physical Infrastructure</td><td>✅ Data centers, hardware, cooling</td><td>—</td></tr><tr><td>Network Infrastructure</td><td>✅ Core networking</td><td>✅ VPC config, security groups</td></tr><tr><td>Operating System</td><td>✅ (Managed services)</td><td>✅ (IaaS — customer patches OS)</td></tr><tr><td>Application</td><td>—</td><td>✅ Code security, updates</td></tr><tr><td>Data</td><td>—</td><td>✅ Encryption, access control</td></tr><tr><td>Identity & Access</td><td>✅ IAM service</td><td>✅ IAM policies, MFA</td></tr></table>` },
        { title:'🔍 CSPM & SIEM', body:`<p><strong>CSPM (Cloud Security Posture Management):</strong> Automatically scans cloud environments for misconfigurations, compliance violations, and vulnerabilities. Provides continuous visibility.</p><p><strong>SIEM (Security Information & Event Management):</strong> Collects and correlates log data from across the organization to detect threats in real-time.</p><p><strong>Together:</strong> CSPM protects configuration → SIEM detects active threats → creating layers of defense in cloud security.</p>` }
    ],
    caseStudies: [],
    flashcards: [
        { front:'Shared Responsibility', back:'Cloud provider secures infrastructure. Customer secures data, access, and application configuration.' },
        { front:'CSPM', back:'Cloud Security Posture Management — auto-detects misconfigurations, compliance issues. Example: flagging public S3 buckets.' },
        { front:'Principle of Least Privilege', back:'Users should only have the minimum access required for their role — nothing more.' },
        { front:'Data at Rest vs Transit', back:'At rest = stored data (encrypt with AES-256). In transit = moving data (encrypt with TLS/SSL).' }
    ]
}
};
